name: openvino-plugins-obs-studio
base: core24
version: v1.1-1-g128e
summary: Intel OpenVINO™ AI plugins for OBS Studio
description: |
   A set of OpenVINO™ based plugins that add AI features to OBS Studio:
    * **Smart Framing** - Detect person(s) / face(s) in a scene, and automatically crop / center / resize around the subjects of interest. 
    * **Background Concealment** – Segment a person in the foreground from background, and allow background to be removed via blur, static image, or virtual green sceen (for chroma keying). 
    * **Face Mesh** – Performs Mediapipe's face mesh pipeline using OpenVINO & OpenCV. Overlays 468 facial key-points onto resultant frame. The intent is a reference / starting point for developers wanting to implement broader face effects. 

website: https://github.com/intel/openvino-plugins-for-obs-studio
contact: https://github.com/canonical/openvino-plugins-obs-studio-snap/issues
issues: https://github.com/intel/openvino-plugins-for-obs-studio/issues
source-code: https://github.com/canonical/openvino-plugins-obs-studio-snap

license: Apache-2.0

grade: stable
confinement: strict

platforms:
  amd64:

slots:
  obs-plugins:
    interface: content
    source:
      read:
        - /${CRAFT_PROJECT_NAME}

parts:
  prepare-hook:
    plugin: nil
    override-build: |
      mkdir -p ${CRAFT_PART_INSTALL}/snap/hooks/
      echo -e '#!/bin/bash\nsnapctl set :obs-plugins snapname='"${CRAFT_PROJECT_NAME}" > ${CRAFT_PART_INSTALL}/snap/hooks/prepare-slot-obs-plugins

  openvino-plugins:
    source: https://github.com/intel/openvino-plugins-for-obs-studio.git
    source-type: git
    source-commit: v1.1-1-g128e
    plugin: dump
    build-environment:
      - OpenVINO_DIR: /snap/openvino-toolkit-2404/current/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/cmake/
      - libobs_DIR: /snap/obs-studio/current/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/cmake/
    build-packages:
      - libopencv-dev
      - cmake
    build-snaps:
      - openvino-toolkit-2404/latest/stable
      - obs-studio/latest/candidate
    override-build: |
      set -eux
      cd $CRAFT_PART_BUILD
      cmake .
      make -j"$(nproc)"

      OBS_PLUGINS_PATH=${CRAFT_PART_INSTALL}/${CRAFT_PROJECT_NAME}/plugins
      OBS_PLUGINS_DATA_PATH=${CRAFT_PART_INSTALL}/${CRAFT_PROJECT_NAME}/data

      mkdir -p $OBS_PLUGINS_PATH $OBS_PLUGINS_DATA_PATH

      for PLUGIN_SO in $(find ${CRAFT_PART_BUILD}/intel64/Release/lib/ -name '*.so'); do
        cp ${PLUGIN_SO} ${OBS_PLUGINS_PATH}/

        PLUGIN_DATA=$(basename ${PLUGIN_SO%.so})
        PLUGIN_DATA=${PLUGIN_DATA#lib}
        mkdir ${OBS_PLUGINS_DATA_PATH}/${PLUGIN_DATA}
      done

      cp -R openvino-models/ ${OBS_PLUGINS_DATA_PATH}/
    stage-packages:
      - libopencv-imgproc406t64
      - libopencv-imgcodecs406t64
      - libopencv-core406t64
    stage-snaps:
      - openvino-toolkit-2404/latest/stable
    organize:
      usr/lib: ${CRAFT_PROJECT_NAME}/lib
